[phases.setup]
nixPkgs = ["python311", "ffmpeg", "gcc"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn server:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 620"
